development:
  adapter: postgresql
  encoding: unicode
  database: myflix2_development
  pool: 5
  username: durrellchamorro
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myflix2_test
  pool: 5
  username: durrellchamorro
  password:

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
