development:
  redistogo_url: <%= ENV["REDISTOGO_URL"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  redistogo_url: <%= ENV["REDISTOGO_URL"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


staging:
  redistogo_url: <%= ENV["REDISTOGO_URL"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
